### ISSUE TITLE
there is no server.go in adnl package

### ISSUE THREAD

**Issue by stevekeol** [startfellows/tongo#10]
To implement the ADNL protocol, there may have the corresponding server.go to hand with client.go in adnl package ?

**Comment by mr-tron** [comment]
Really i found a problem. Current package adnl doesn't implement ADNL. Naming problem. That's just liteserver trnsport protocol with key genertation from adnl. But ADNL really have different schema.

**Comment by salemx33** [comment]
UQCoWfrwRQrM_SECo4XyqXxUDiICn8ggdY8OVlZOX7gtPqbO

**Comment by MMashayekh23** [comment]
Ok
